# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: python:3.7-alpine3.11
    # - image: amazon/aws-cli

# commands:
#   print_pipeline_id:
#     description: prints the Circle CI Workflow ID
#     parameters:
#       to:
#         type: string
#         default: "Hey Hey"
#     steps:
#     - run: echo workflow_id is << parameters.to >>    

jobs:
  configure_infrastructure:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["aa:ba:25:18:db:4f:52:b8:c8:79:42:70:60:74:4a:29"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible      
      - run:
          name: Configure Server
          command: |
            ansible-playbook -i hello-world-playbook/inventory.txt hello-world-playbook/playbook.yml

  # create_infrastructure:
  #   <<: *defaults
  #   working_directory: hello-world-stack
  #   steps:
  #     - checkout
  #     - run:
  #         name: print current dir
  #         command: ls hello-world-stack
  #     # - run:
  #     #     name: Add permission to create stack
  #     #     command: source /hello-world-stack/create.sh

  #     - run:
  #         name: Create infastructure stack
  #         command: |
  #           hello-world-stack/create.sh ec2stack \
  #           hello-world-stack/create-ec2.yaml \
  #           hello-world-stack/create-ec2-parameters.json

  # job_to_fail:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: This job is intended to fail
  #         command: return 1

  #     - run:
  #         name: This is a rescue step if this job fails
  #         command: echo The App is on fire
  #         when: on_fail  

  # print_workflow_id:
  #   <<: *defaults
  #   steps:
  #     - print_pipeline_id:
  #         to: $CIRCLE_WORKFLOW_ID

  # save_hello_world_output:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run:
  #         name: Helo world file out
  #         command: |
  #           echo "text to output here" > ~/output.txt
  #     - persist_to_workspace:
  #         root: ~/
  #         paths:
  #           - output.txt

  # print_output_file:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - attach_workspace:
  #         at: ~/ 
  #     - run:
  #         name: Read output.txt file and print whats inside.
  #         command: |
  #            cat ~/output.txt
                
# Orchestrate or schedule a set of jobs
workflows:
  default:
    jobs:
      - configure_infrastructure
      # - create_infrastructure
      # - job_to_fail
      # - print_workflow_id
      # - save_hello_world_output
      # - print_output_file:
      #     requires: [save_hello_world_output]

