version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: echo destroied ec2

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: echo created ec2
      - run: return 1
      - run:
          name: Destroy environment
          command: echo destroied ec2
          when: on_fail

workflows:
  default:
    jobs:
      - build