# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
         name: Print hello
         command: |
           echo "hello"  
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          name: Print world
          command: |
            echo "world"
  print_noaj:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print noaj
          command: |
            echo "I " $NOAJ            
# Orchestrate or schedule a set of jobs
workflows:
  default:
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_noaj    

